-- Create the employees table
CREATE TABLE Employeees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(50),
    last_name   VARCHAR2(50)
);

-- Insert sample records
INSERT INTO Employeees (first_name, last_name) VALUES ('Aaron', 'Smith');
INSERT INTO Employeees (first_name, last_name) VALUES ('Ben', 'Miller');
INSERT INTO Employeees (first_name, last_name) VALUES ('Carl', 'Davis');
INSERT INTO Employeees (first_name, last_name) VALUES ('Charlie', 'Brown');
INSERT INTO Employeees (first_name, last_name) VALUES ('David', 'Wilson');
INSERT INTO Employeees (first_name, last_name) VALUES ('Alex', 'Jones');

-- Applying search
SELECT * 
FROM Employeees 
WHERE first_name BETWEEN 'a' AND 'c'; 
-- It shows nothing because text literals inside single quotes are strictly case-sensitive.
--The query is looking for names between lowercase 'a' and lowercase 'c', But in the database, the names are capitalized ('A'aron, 'B'en, 'A'lex).

-- Search but ignore whether the letters are uppercase or lowercase: returns 5 rows
SELECT * FROM Employeees WHERE REGEXP_LIKE(first_name, '^[a-c]', 'i');